import { ChakraProviders } from "./chakraProviders";
import StoreProvider from "../lib/redux/StoreProvider";

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <ChakraProviders>{children}</ChakraProviders>
        </StoreProvider>
      </body>
    </html>
  );
}

export default RootLayout;
